---
# Role check tasks

- block:
    - name: assert platform is supported
      assert:
        that:
          - distribution in docker_provisioner_supported_distributions
          - >-
            ansible_facts.distribution_version
            is version(docker_provisioner_supported_versions[distribution], ">=")
      vars:
        distribution: "{{ ansible_facts.distribution | lower }}"
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::check
