---
# Get containers ssh port maps

- block:
    - name: >-
        get ssh mapped ports
        {{ docker_provisioner_get_ports_suffix }}
      shell: >-
        {{ command_start
           + " "
           + '"'
           + container.ssh_port
             | default(docker_provisioner_container_ssh_port)
             | string
           + "/tcp"
           + '"'
           + command_end
           + " "
           + container.name }}
      when: >-
        container.state
        | default(docker_provisioner_container_state)
        in ["present", "started"]
      register: docker_provisioner_get_ports_result
      changed_when: false
      failed_when: false
      loop: "{{ docker_provisioner_get_ports_containers }}"
      loop_control:
        label: >-
          {{ container.name }}
          {{ docker_provisioner_get_ports_ips[container.name] }}
        loop_var: container
      check_mode: no
      vars:
        command_start: >-
          docker inspect --format='{''{(index (index .NetworkSettings.Ports
        command_end: >-
          ) 0).HostPort}''}'

    - name: >-
        setup fact with the ssh mapped ports
        {{ docker_provisioner_get_ports_suffix }}
      set_fact:
        "{{ docker_provisioner_get_ports_fact_name }}": >-
          {{ lookup('template', 'ssh_mapped_ports.j2') | from_yaml }}
      vars:
        results: "{{ docker_provisioner_get_ports_result.results }}"

  tags:
    - role::docker_provisioner
    - role::docker_provisioner::containers
