---
# Setup connection for docker containers that use ssh

- block:
    - name: create .ssh directory
      file:
        path: "~/.ssh"
        state: directory
        mode: 0700

    - name: get containers ssh host port mapping
      shell: >-
        {{ command_start
           + " "
           + '"'
           + container.ssh_port
             | default(docker_provisioner_container_ssh_port)
             | string
           + "/tcp"
           + '"'
           + command_end
           + " "
           + container.name }}
      when: >-
        container.state
        | default(docker_provisioner_container_state) in ["present", "started"]
      register: docker_provisioner_get_ssh_mapped_port_result
      changed_when: false
      failed_when: false
      loop: "{{ docker_provisioner_containers }}"
      loop_control:
        label: "{{ container.name }}"
        loop_var: container
      check_mode: no
      vars:
        command_start: >-
          docker inspect --format='{''{(index (index .NetworkSettings.Ports
        command_end: >-
          ) 0).HostPort}''}'

    - block:
        - name: setup containers ssh connector
          add_host:
            name: "{{ container.1.name }}"
            ansible_host: "{{ host }}"
            ansible_port: "{{ container_ssh_port }}"
            ansible_connection: ssh
          changed_when: false
          loop: >-
            {{ query('indexed_items', docker_provisioner_containers) }}
          loop_control:
            label: "{{ container.1.name }}"
            loop_var: container

        - name: wait for docker containers ssh port
          wait_for:
            host: "{{ ansible_host }}"
            port: "{{ container_ssh_port }}"
            timeout: 60
            connect_timeout: 5
          changed_when: false
          loop: >-
            {{ query('indexed_items', docker_provisioner_containers) }}
          loop_control:
            label: >-
              {{ container.1.name
                 + " "
                 + ips[container.0]
                   | default('') }}
            loop_var: container

        - name: gather containers ssh public keys
          shell: >-
            ssh-keyscan -T 10
            -p {{ container_ssh_port }}
            {{ host }}
          changed_when: false
          loop: >-
            {{ query('indexed_items', docker_provisioner_containers) }}
          register: docker_provisioner_get_public_keys_result
          loop_control:
            label: "{{ container.1.name }}"
            loop_var: container
          check_mode: no

        - name: setup ssh known_hosts entries in docker host
          known_hosts:
            name: "{{ container_knownhosts_address }}"
            key: "{{ container_public_key }}"
            state: present
          loop: >-
            {{ query('indexed_items', docker_provisioner_containers) }}
          loop_control:
            label: >-
              {{ container.1.name }}
              {{ ips[container.0] | default('') }}
            loop_var: container

        - name: setup ssh known_hosts entries in ansible controller
          local_action: known_hosts
          args:
            name: "{{ container_knownhosts_address }}"
            key: "{{ container_public_key }}"
            state: present
          loop: >-
            {{ query('indexed_items', docker_provisioner_containers) }}
          loop_control:
            label: >-
              {{ container.1.name }}
              {{ ips[container.0] | default('') }}
            loop_var: container
          vars:
            container_known_hosts_ip: "[{{ ansible_host }}]"
      when:
        - >
          container.1.state
          | default(docker_provisioner_container_state)
          in ["present", "started"]
        - >
          container_ssh_port | length > 0
        - >
          container.1.ssh_port
          | default(docker_provisioner_container_ssh_port)
          | string
          | length > 0
        - >
          docker_provisioner_containers_deploy_result.results[container.0]
          is changed
      vars:
        host: >-
          {{ hostvars[inventory_hostname].ansible_host }}
        public_keys: >-
          {{ docker_provisioner_get_public_keys_result.results
             | map(attribute="stdout")
             | list }}
        container_ssh_port: >-
          {{ mapped_ports[container.0] }}
        container_knownhosts_address: >-
          {{ (container_ssh_port | string == "22")
             | ternary(host, "[" + host + "]:" + container_ssh_port) }}
        container_public_key: >-
          {{ public_keys[container.0]
             | regex_replace("[^\n].* (.*) ",
                             container_knownhosts_address + " \1 ") }}
  vars:
    mapped_ports: >-
      {{ docker_provisioner_get_ssh_mapped_port_result.results
         | map(attribute="stdout")
         | list }}
    ips: "{{ docker_provisioner_containers_ips }}"
    default_ssh_port: "{{ docker_provisioner_container_ssh_port }}"
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::containers
