---
# Setup connection of docker containers that use tty

- block:
    - name: setup containers docker connector
      add_host:
        name: "{{ container.1.name }}"
        ansible_host: "{{ inventory_hostname }}"
        ansible_port: >-
          {{ hostvars[inventory_hostname][ansible_port] | default(22) }}
        docker_ip: >-
          {{ docker_provisioner_containers_ips[container.0] }}
        ansible_connection: docker
      when:
        - >
          not container.1.ssh_port
              | default(docker_provisioner_container_ssh_port)
              | string
              | length > 0
        - >
          container.state
          | default(docker_provisioner_container_state)
          in ["present", "started"]
      changed_when: false
      loop: "{{ query('indexed_items', docker_provisioner_containers) }}"
      loop_control:
        label: "{{ container.1.name }}"
        loop_var: container

    - name: ensure that is possible to connect to docker connector containers
      shell:
        docker exec -t {{ item.name }}
        echo '{{ test_message }}'
      when:
        - >
          not container.1.ssh_port
              | default(docker_provisioner_container_ssh_port)
              | string
              | length > 0
        - >
          item.state
          | default(docker_provisioner_container_state)
          in ["present", "started"]
      changed_when: false
      register: docker_provisioner_tty_connection_result
      failed_when: >-
          not docker_provisioner_tty_connection_result.stdout
              is search(test_message)
      loop: "{{ docker_provisioner_containers }}"
      vars:
        test_message: "Docker container is up"
      loop_control:
        label: "{{ item.name }}"
  vars:
    default_options: "{{ docker_provisioner_container_options }}"
    default_containers: "{{ docker_provisioner_container_options }}"
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::containers
