---
# Get containers ip addresses

- block:
    - name: >-
        get the ip addresses
        {{ docker_provisioner_get_ips_task_suffix }}
      shell: >-
        docker inspect --format='{''{.NetworkSettings.IPAddress}''}'
        {{ container.name }}
      register: docker_provisioner_provisioned_get_ip_result
      when: >-
        container.state
        | default(docker_provisioner_container_state)
        in ["present", "started"]
      loop: "{{ docker_provisioner_get_ips_containers }}"
      loop_control:
        label: "{{ container.name }}"
        loop_var: container
      changed_when: false
      check_mode: no

    - name: >-
        setup fact with the ips
        {{ docker_provisioner_get_ips_task_suffix }}
      set_fact:
        "{{ docker_provisioner_get_ips_fact_name }}": >-
          {{ lookup('template', 'containers_ips.j2') | from_yaml }}
      vars:
        results: "{{ docker_provisioner_provisioned_get_ip_result.results }}"

  tags:
    - role::docker_provisioner
    - role::docker_provisioner::containers
