---

- name: Sequential docker images deploy
  community.docker.docker_image:
    name: "{{ image.name }}"
    build: "{{ docker_provisioner_image_build }}"
    force_source: >-
      {{ image.force
         | default(docker_provisioner_image_force) }}
    source: >-
        {{ image.source
           | default(docker_provisioner_image_source) }}
    state: >-
      {{ image.state
         | default(docker_provisioner_image_state) }}
    repository: >-
      {{ image.repository
         | default(docker_provisioner_image_repository) }}
    timeout: >-
      {{ image.timeout
         | default(docker_provisioner_image_timeout) }}
    push: >-
      {{ image.push
         | default(docker_provisioner_image_push) }}
  loop: "{{ docker_provisioner_images }}"
  loop_control:
    label: "{{ image.name }}"
    loop_var: image
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::images
