---
# Setup docker images sequentially

- name: Sequential docker images deploy
  docker_image:
    name: "{{ image.name }}"
    build:
      dockerfile: >-
        {{ image.dockerfile
           | default(docker_provisioner_image_dockerfile) }}
      args: >-
        {{ image.buildargs
           | default(docker_provisioner_image_buildargs) }}
      path: >-
        {{ image.path
           | default(docker_provisioner_image_path) }}
      pull: yes
    force_source: >-
      {{ image.force
         | default(docker_provisioner_image_force) }}
    rm: >-
      {{ image.rm
         | default(docker_provisioner_image_rm) }}
    source: build
    state: >-
      {{ image.state
         | default(docker_provisioner_image_state) }}
    repository: >-
      {{ image.repository
         | default(docker_provisioner_image_repository) }}
    timeout: >-
      {{ image.timeout
         | default(docker_provisioner_image_timeout) }}
    push: >-
      {{ image.push
         | default(docker_provisioner_image_push) }}
  loop: "{{ docker_provisioner_images }}"
  loop_control:
    label: "{{ image.name }}"
    loop_var: image
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::images
