---
# Setup docker images

- name: deploy docker images
  docker_image:
    name: "{{ image.name }}"
    dockerfile: >-
      {{ image.dockerfile
         | default(docker_provisioner_image_dockerfile) }}
    buildargs: >-
      {{ image.buildargs
         | default(docker_provisioner_image_buildargs) }}
    force: >-
      {{ image.force
         | default(docker_provisioner_image_force) }}
    path: >-
      {{ image.path
         | default(docker_provisioner_image_path) }}
    rm: >-
      {{ image.rm
         | default(docker_provisioner_image_rm) }}
    state: >-
      {{ image.state
         | default(docker_provisioner_image_state) }}
    timeout: >-
      {{ image.timeout
         | default(docker_provisioner_image_timeout) }}
  loop: "{{ docker_provisioner_images }}"
  loop_control:
    label: "{{ image.name }}"
    loop_var: image
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::images
