---
# Setup docker images

- import_tasks: "{{ docker_provisioner_images_provisioning_include }}"
  vars:
    method: "{{ docker_provisioner_images_provisioning_method }}"
    docker_provisioner_images_provisioning_include: >-
      {{ (method == "asynchronous")
         | ternary("images_asynchronous.yml",
                   "images_sequential.yml") }}
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::images
