---
# Setup docker images

- import_tasks: "{{ playbook }}"
  vars:
    method: "{{ docker_provisioner_images_provisioning_method }}"
    playbook: >-
      {{ (method == "asynchronous")
         | ternary("images_provisioning_asynchronous.yml",
                   "images_provisioning_sequential.yml") }}
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::images
