---
# Load default images options

- block:

  - name: search default images
    find:
      paths: "{{ role_path }}/defaults/images"
      patterns: "*.yml"
    register: docker_provisioner_search_default_images_result

  - name: load default images
    include_vars:
      file: "{{ file.path }}"
      name: docker_provisioner_default_image
    with_items: "{{ docker_provisioner_search_default_images_result.files }}"
    loop_control:
      label: "{{ file.path }}"
      loop_var: file
    register: docker_provisioner_load_default_images_result

  - name: setup fact with default images
    set_fact:
      docker_provisioner_default_images: >-
        {{ docker_provisioner_load_default_images_result.results
          | map(attribute="ansible_facts.docker_provisioner_default_image")
          | list }}

  tags:
    - role::docker_provisioner
    - role::docker_provisioner::images
