---

- name: Setup images
  include_tasks: images.yml
  when: docker_provisioner_images | length > 0
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::images

- name: Setup containers
  include_tasks: containers.yml
  when: docker_provisioner_containers | length > 0
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::containers
