---
# Setup docker images

- block:

  # We need to setup this fact to ensure proper interaction with the
  # randomize_names filter. It the fact is not setup each role execution could
  # lead to a new random name generation every time the variable value is
  # rendered.

  - name: setup fact with docker provisioner images
    set_fact:
      docker_provisioner_images: "{{ docker_provisioner_images }}"

  - name: setup docker images
    docker_image:
      name: "{{ image.name }}"
      dockerfile: >-
        {{ image.dockerfile
          | default(docker_provisioner_image_dockerfile) }}
      buildargs: >-
        {{ image.buildargs
          | default(docker_provisioner_image_buildargs) }}
      force: >-
        {{ image.force
          | default(docker_provisioner_image_force) }}
      path: >-
        {{ image.path
          | default(docker_provisioner_image_path) }}
      rm: >-
        {{ image.rm
          | default(docker_provisioner_image_rm) }}
      state: >-
        {{ image.state
          | default(docker_provisioner_image_state) }}
    with_items: "{{ docker_provisioner_images }}"
    loop_control:
      label: "{{ image.name }}"
      loop_var: image

  tags:
    - role::docker_provisioner
    - role::docker_provisioner::containers
