---
# Setup docker containers

- block:
  - name: start docker containers
    docker_container:
      name: >-
        {{ container.name }}
      image: >-
        {{ container.image }}
      privileged: >-
        {{ container.privileged | default(default_options.privileged) }}
      state: >-
        {{ container.state | default(default_options.state) }}
      restart: >-
        {{ container.restart | default(default_options.restart) }}
      tls: >-
        {{ container.tls | default(default_options.tls) }}
      stop_timeout: >-
        {{ container.stop_timeout | default(default_options.stop_timeout) }}
      tty: >-
        {{ container.tty | default(default_options.tty) }}
      expose: >-
        {{ container.expose | default(default_options.expose) }}
      command: >-
        {{ container.command | default(default_options.command) }}
      env: >-
        {{ container.env | default(default_options.env) }}
      links: >-
        {{ container.links | default(default_options.links) }}
      volumes: >-
        {{ container.volumes | default(default_options.volumes) }}
    with_items: >
      {{ docker_provisioner_containers }}
    loop_control:
      label: "{{ container.name }}"
      loop_var: container

  - block:
    - name: get containers ip addresses
      shell: >-
        docker inspect --format='{''{.NetworkSettings.IPAddress}''}'
        {{ container.name }}
      register: docker_provisioner_get_ip_result
      when: >
        "{{ container.state | default(default_options.state) }}"
          in ["present", "started"]
      with_items: >
        {{ docker_provisioner_containers }}
      loop_control:
        label: "{{ container.name }}"
        loop_var: container
      changed_when: false

    - name: associate auth info / group info to containers
      add_host:
        name: >-
          {{ container.1.name }}
        ansible_user: >-
          {{ container.1.ansible_user | default(default_options.ansible_user) }}
        ansible_password: >-
          {{ container.1.ansible_ssh_pass
            | default(default_options.ansible_password) }}
        groups: >-
          {{ container.1.groups | default(default_options.groups) }}
      when: >
        "{{ container.state | default(default_options.state) }}"
          in ["present", "started"]
      with_indexed_items: >
        {{ docker_provisioner_containers }}
      changed_when: false
      loop_control:
        label: "{{ container.1.name }}"
        loop_var: container

    - include: setup_containers_tty.yml
    - include: setup_containers_ssh.yml

  vars:
    containers: "{{ docker_provisioner_containers }}"
    default_options: "{{ docker_provisioner_container_options }}"
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::containers
