---
# Setup connection for docker containers that use ssh

- block:

  - name: setup connection of docker containers that don't use tty
    add_host:
      name: "{{ container.1.name }}"
      ansible_host: >-
        {{ docker_provisioner_ip_result.results[container.0].stdout }}
      docker_ip: >-
        {{ docker_provisioner_ip_result.results[container.0].stdout }}
    with_indexed_items: >
      {{ docker_provisioner_containers | default(default_containers) }}
    when:
      - not container.tty | default(default_values.tty)
      - >
        "{{ container.1.state | default(default_values.state) }}"
          in ["present", "started"]
    changed_when: false
    loop_control:
      label: "{{ container.1.name }}"
      loop_var: container

  - name: wait for ssh of the docker containers that don't use tty
    wait_for:
      host: "{{ hostvars[container.name]['ansible_host'] }}"
      port: 22
      timeout: 60
      connect_timeout: 5
    changed_when: false
    when:
      - not container.tty | default(default_values.tty)
      - >
        "{{ container.state | default(default_values.state) }}"
          in ["present", "started"]
    with_items: >
      {{ docker_provisioner_containers | default(default_containers) }}
    loop_control:
      label: >-
        {{ container.name }}
        {{ hostvars[container.name]['ansible_host'] | default('') }}
      loop_var: container

  vars:
    default_values: "{{ docker_provisioner_default_container }}"
    default_containers: "{{ docker_provisioner_default_containers }}"
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::containers
