---
# Setup connection for docker containers that use ssh

- block:

  - name: setup containers ssh connection
    add_host:
      name: "{{ container.1.name }}"
      ansible_host: >-
        {{ docker_provisioner_get_ip_result.results[container.0].stdout }}
      docker_ip: >-
        {{ docker_provisioner_get_ip_result.results[container.0].stdout }}
    with_indexed_items: >
      {{ docker_provisioner_containers }}
    when:
      - not container.1.tty | default(default_options.tty)
      - >
        "{{ container.1.state | default(default_options.state) }}"
          in ["present", "started"]
    changed_when: false
    loop_control:
      label: "{{ container.1.name }}"
      loop_var: container

  - name: ensure that is possible to connect with ssh to docker containers
    wait_for:
      host: "{{ hostvars[container.name]['ansible_host'] }}"
      port: 22
      timeout: 60
      connect_timeout: 5
    changed_when: false
    when:
      - not container.tty | default(default_options.tty)
      - >
        "{{ container.state | default(default_options.state) }}"
          in ["present", "started"]
    with_items: >
      {{ docker_provisioner_containers }}
    loop_control:
      label: >-
        {{ container.name }}
        {{ hostvars[container.name]['ansible_host'] | default('') }}
      loop_var: container

  vars:
    default_options: "{{ docker_provisioner_container_options }}"
    default_containers: "{{ docker_provisioner_container_options }}"
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::containers
