---
# Setup connection of docker containers that use tty

- block:

  - name: setup containers tty
    add_host:
      name: "{{ container.1 }}"
      ansible_host: "{{ container.1 }}"
      docker_ip: >-
        {{ docker_provisioner_get_ip_result.results[container.0].stdout }}
      ansible_connection: docker
    when:
      - >
        docker_provisioner_containers[container.1].tty
          | default(docker_provisioner_container_tty)
      - >
        "{{ docker_provisioner_containers[container.1].state
          | default(docker_provisioner_container_state) }}" == "started"
    changed_when: false
    with_indexed_items: "{{ docker_provisioner_containers | list }}"
    loop_control:
      label: "{{ container.1 }}"
      loop_var: container

  - name: ensure that is possible to connect with tty to docker containers
    raw: "echo Docker contaimer is up"
    when:
      - >
        docker_provisioner_containers[item].tty
          | default(docker_provisioner_container_tty)
      - >
        "{{ docker_provisioner_containers[item].state
          | default(docker_provisioner_container_state) }}" == "started"
    changed_when: false
    delegate_to: "{{ item }}"
    with_items: "{{ docker_provisioner_containers | list }}"

  vars:
    default_options: "{{ docker_provisioner_container_options }}"
    default_containers: "{{ docker_provisioner_container_options }}"
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::containers
