---
# Setup docker images
- debug: var=test
- debug: var=docker_provisioner_images
- debug: var=docker_provisioner_image_options

- name: setup docker images
  docker_image:
    name: "{{ name }}"
    dockerfile: "{{ images[name].dockerfile | default(defaults.dockerfile) }}"
    buildargs: "{{ images[name].buildargs | default(defaults.buildargs) }}"
    force: "{{ images[name].force | default(defaults.force) }}"
    path: "{{ images[name].path | default(defaults.path) }}"
    rm: "{{ images[name].rm | default(defaults.rm) }}"
    state: "{{ images[name].state | default(defaults.state) }}"
  with_items: "{{ images }}"
  loop_control:
    loop_var: name
  vars:
    images: "{{ docker_provisioner_images }}"
    defaults: "{{ docker_provisioner_image_options }}"
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::images
