---
# Setup docker images

- name: setup docker images
  docker_image:
    name: "{{ name }}"
    dockerfile: >-
      {{ docker_provisioner_images[name].dockerfile
        | default(docker_provisioner_image_dockerfile) }}
    buildargs: >-
      {{ docker_provisioner_images[name].buildargs
        | default(docker_provisioner_image_buildargs) }}
    force: >-
      {{ docker_provisioner_images[name].force
        | default(docker_provisioner_image_force) }}
    path: >-
      {{ docker_provisioner_images[name].path
        | default(docker_provisioner_image_path) }}
    rm: >-
      {{ docker_provisioner_images[name].rm
        | default(docker_provisioner_image_rm) }}
    state: >-
      {{ docker_provisioner_images[name].state
        | default(docker_provisioner_image_state) }}
  with_items: "{{ docker_provisioner_images }}"
  loop_control:
    loop_var: name
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::images
