---
# Setup docker images

- name: setup docker images
  docker_image:
    name: "{{ image.name }}"
    dockerfile: "{{ image.dockerfile | default(default_values.dockerfile) }}"
    buildargs: "{{ image.buildargs | default(default_values.buildargs) }}"
    force: "{{ image.force | default(default_values.force) }}"
    path: "{{ image.path | default(default_values.path) }}"
    rm: "{{ image.rm | default(default_values.rm) }}"
    state: "{{ image.state | default(default_values.state) }}"
  with_items: "{{ docker_provisioner_images | default(default_images) }}"
  loop_control:
    label: "{{ image.name }}"
    loop_var: image
  vars:
    default_values: "{{ docker_provisioner_default_image }}"
    default_images: "{{ docker_provisioner_default_images }}"
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::images
