---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  become: yes
  roles:
    - role: amtega.packages
      vars:
        packages_os:
          all:
            all:
              python3: present

        packages_python:
          all:
            all:
              docker: present

    - role: amtega.python_semanage
    - role: amtega.docker_engine
